### ISSUE TITLE
Crash on socket.timeout: timed out

### ISSUE THREAD

**Issue by ways** [mairas/hysen#12]
Hi

I'm on latest version. I sometimes get these errors:

> Mar 01 09:11:22 home-assistant hass[6262]: 2019-03-01 09:11:22 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Mar 01 09:11:22 home-assistant hass[6262]: Traceback (most recent call last):
> Mar 01 09:11:22 home-assistant hass[6262]:   File "/root/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_pl
> atform_call
> Mar 01 09:11:22 home-assistant hass[6262]:     await getattr(entity, func)(**data)
> Mar 01 09:11:22 home-assistant hass[6262]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
> Mar 01 09:11:22 home-assistant hass[6262]:     result = self.fn(*self.args, **self.kwargs)
> Mar 01 09:11:22 home-assistant hass[6262]:   File "/root/.homeassistant/custom_components/hysen/climate.py", line 673, in turn_off
> Mar 01 09:11:22 home-assistant hass[6262]:     self._broadlink_device.set_power(HYSEN_POWEROFF)
> Mar 01 09:11:22 home-assistant hass[6262]:   File "/root/homeassistant/lib/python3.6/site-packages/broadlink/__init__.py", line 725, in set_power
> Mar 01 09:11:22 home-assistant hass[6262]:     self.send_request(bytearray([0x01,0x06,0x00,0x00,remote_lock,power]) )
> Mar 01 09:11:22 home-assistant hass[6262]:   File "/root/homeassistant/lib/python3.6/site-packages/broadlink/__init__.py", line 616, in send_request
> Mar 01 09:11:22 home-assistant hass[6262]:     response = self.send_packet(0x6a, request_payload)
> Mar 01 09:11:22 home-assistant hass[6262]:   File "/root/homeassistant/lib/python3.6/site-packages/broadlink/__init__.py", line 305, in send_packet
> Mar 01 09:11:22 home-assistant hass[6262]:     response = self.cs.recvfrom(2048)
> Mar 01 09:11:22 home-assistant hass[6262]: socket.timeout: timed out
> Mar 01 09:12:23 home-assistant hass[6262]: 2019-03-01 09:12:23 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Mar 01 09:12:23 home-assistant hass[6262]: Traceback (most recent call last):
> Mar 01 09:12:23 home-assistant hass[6262]:   File "/root/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 289, in _handle_service_pl
> atform_call

Since it says timeout, I'm guessing the hysen doesn't reply. Should this be handled better instead of a crash?

**Comment by mcc05** [comment]
This should be fixed in latest versions as the self._broadlink_device.set_power(HYSEN_POWEROFF) is now not called directly and goes via a code block with timeout and exception processing

**Comment by ways** [comment]
Thank you! Seems to work fine.
