### ISSUE TITLE
Make week_day & week_end attributes JSON compliant

### ISSUE THREAD

**Issue by FF-Fox** [mairas/hysen#22]
Hi,

This is more broadlink-library issue, but it's easily fixable in the hysen-climate device ;)

For more flexibility, the week_day & week_end attribute that is returned should be JSON compliant. This is not the case in the broadlink-library since they use single quotes instead of double quotes.

You can fix this by changing line 657 & 658 in climate.py from
```
        attr['week_day'] = str(self._week_day)
        attr['week_end'] = str(self._week_end)
``` 
to 
```
        attr['week_day'] = str(self._week_day).replace("'",'"')
        attr['week_end'] = str(self._week_end).replace("'",'"')
```

After doing so, you get alot more flexibility for getting/setting the schedule in HA.

**Comment by mcc05** [comment]
done
