### ISSUE TITLE
Failed to connect to Broadlink Hysen device

### ISSUE THREAD

**Issue by elmerenges** [mairas/hysen#25]
Hello!

Sometimes I get this error:
2020-02-06 18:42:40 ERROR (MainThread) [custom_components.hysen.climate] Failed to connect to Broadlink Hysen device MAC:34:EA:xx:xx:xx:xx, IP:192.168.0.xx, Error:timed out

I am on version 0.105.1.

The app is working perfectly.

Configuration:
climate:
  - platform: hysen
    devices:
      main_thermostat:
        name: Main Thermostat
        host: 192.168.0.xx
        mac: "34:EA:xx:xx:xx:xx"

I hope you can help, and thank you for this component.

**Comment by mcc05** [comment]
Cant reproduce, if still issue let me know
