### ISSUE TITLE
No module named 'PyCRC'

### ISSUE THREAD

**Issue by zaharpecherin** [mairas/hysen#26]
I get error: `ERROR (SyncWorker_5) [custom_components.hysen.climate] Failed to get Data from Broadlink Hysen Device:climate.main_thermostat,:No module named 'PyCRC'`.

**Comment by mamrai1** [comment]
fixed by changing manifest.json:
{
  "domain": "hysen",
  "name": "Hysen Thermostat Controller",
  "documentation": "",
  "requirements": ["broadlink==0.13.0", "pythoncrc"],
  "dependencies": [
    "http"
  ],
  "codeowners": ["@markcarter", "@iwantto.com"]
}

**Comment by mamrai1** [comment]
latest change of homeassistant core/scripts/gen_requirements_all.py  (became case insensitive) installs pycrc instead of PyCRC..

**Comment by mcc05** [comment]
@mamrai1 thank you was just looking at this :)

**Comment by mcc05** [comment]
Committed manifest.json change thanks to @mamrai1 for the fix

**Comment by alb147** [comment]
> 
> 
> fixed by changing manifest.json:
> {
> "domain": "hysen",
> "name": "Hysen Thermostat Controller",
> "documentation": "",
> "requirements": ["broadlink==0.13.0", "pythoncrc"],
> "dependencies": [
> "http"
> ],
> "codeowners": ["@MarkCarter", "@iwantto.com"]
> }

working for me in the Home Assistant 0.107.7 version
Thanks

**Comment by melodyre** [comment]
> fixed by changing manifest.json:
> {
> "domain": "hysen",
> "name": "Hysen Thermostat Controller",
> "documentation": "",
> "requirements": ["broadlink==0.13.0", "pythoncrc"],
> "dependencies": [
> "http"
> ],
> "codeowners": ["@MarkCarter", "@iwantto.com"]
> }

where to find the manifest.json file?
