### ISSUE TITLE
No module named PyCRC

### ISSUE THREAD

**Issue by joemadd3n** [mairas/hysen#28]
Running Home Assistant 0.107.7
Supervisor 213
Log Details (ERROR)
Logger: custom_components.hysen.climate
Source: custom_components/hysen/climate.py:891
First occurred: 8:53:42 PM (3 occurrences)
Last logged: 8:54:04 PM

Failed to get Data from Broadlink Hysen Device:climate.main_thermostat,:No module named 'PyCRC'

**Comment by eifinger** [comment]
You have to update this component to the newest release

**Comment by eifinger** [comment]
You have to update this component to the newest release

**Comment by joemadd3n** [comment]
`Requirement already up-to-date: PyCRC in /usr/local/lib/python3.7/site-packages (0.9.2)`

What I get when I attempt to do this.

**Comment by joemadd3n** [comment]
Fixed using closed issue https://github.com/mairas/hysen/issues/26
Apologies.
