### ISSUE TITLE
Long home assistant startup time

### ISSUE THREAD

**Issue by DangerD256** [mairas/hysen#29]
After adding this plugin and 5 thermostats, config check/restart takes around 2 minutes and cpu load 100% during this time, is there any way to make it faster?

![image](https://user-images.githubusercontent.com/17032489/78528219-8a51f880-77e7-11ea-9252-354d03af0f44.png)

**Comment by mcc05** [comment]
Are you using auto discovery or fixed ip entries?

**Comment by mcc05** [comment]
Closing due to no more information provided

**Comment by DangerD1024** [comment]
it's okay now, maybe after ha update so it started to run everything asynchronously.
