### ISSUE TITLE
name ‘calculate_crc16’ is not defined

### ISSUE THREAD

**Issue by akacruel** [mairas/hysen#30]
After update Home Assistant (Hassio) from 0.108.5 to 0.108.6 in log happens the next error:
Logger: custom_components.hysen.climate
Source: custom_components/hysen/climate.py:891
Failed to get Data from Broadlink Hysen Device:climate.main_thermostat,:name ‘calculate_crc16’ is not defined

**Comment by eifinger** [comment]
I opened a PR against the broadlink lib fixing the issue: https://github.com/mjg59/python-broadlink/pull/344

**Comment by davanda** [comment]
> I opened a PR against the broadlink lib fixing the issue: [mjg59/python-broadlink#344](https://github.com/mjg59/python-broadlink/pull/344)

Hi,
how can I fix on Home Assistant? 
Where can I find the file I want to edit?
Thanks

**Comment by mcc05** [comment]
Fixed
