### ISSUE TITLE
Unable to connect to Thermostat

### ISSUE THREAD

**Issue by boutch** [mairas/hysen#37]
Hello,

Thank you for this component! 

I have just installed the latest version from the master branch and I can't connect to 3 of my thermostats.

I have 4 Beok/Floureon thermostats on my config file as follow, only climate.parents_uf is available in Home Assistant. What am I doing wrong?

climate:
  - platform: hysen
    devices:
      lr_extension_uf:
        name: LR Extension UF
        host: 192.168.30.167
        mac: "34:EA:XX:XX:XX:XX"
      parents_uf:
        name: Parents UF
        host: 192.168.30.44
        mac: "34:EA:XX:XX:XX:XX"
      living_room_uf:
        name: Parents UF
        host: 192.168.30.73
        mac: "34:EA:XX:XX:XX:XX"
      bathroom_uf:
        name: Bathroom UF
        host: 192.168.30.38
        mac: "34:EA:XX:XX:XX:XX"

2020-06-21 21:20:12 ERROR (MainThread) [custom_components.hysen.climate] Failed to connect to Broadlink Hysen device MAC:34:EA:XX:XX:XX:XX, IP:192.168.30.167, Error:[Errno 9] Bad file descriptor
2020-06-21 21:20:13 ERROR (MainThread) [custom_components.hysen.climate] Failed to connect to Broadlink Hysen device MAC:34:EA:XX:XX:XX:XX, IP:192.168.30.73, Error:[Errno 9] Bad file descriptor
2020-06-21 21:20:14 ERROR (MainThread) [custom_components.hysen.climate] Failed to connect to Broadlink Hysen device MAC:34:EA:XX:XX:XX:XX, IP:192.168.30.38, Error:[Errno 9] Bad file descriptor

Thank you

**Comment by mcc05** [comment]
Yep sorry after a while I got the same, haven't figured out what the issue is yet so have reverted to older broadlink code for now. Please try this and let me know any errors you get.

**Comment by boutch** [comment]
No luck, now I am getting Timeout errors. 

2020-06-21 23:06:17 ERROR (MainThread) [custom_components.hysen.climate] Failed to connect to Broadlink Hysen device MAC:34:EA:XX:XX:XX:XX, IP:192.168.30.44, Error:timed out

I know they are supported because I was using https://github.com/algirdasc/hass-components/tree/master/floureon but Home assistant became very very slow and froze after a few hours. 

I am trying to read the code and understand how the floureon component has it working and the hysen not but I am bit struggling... The floureon component is using the broadlink python library so it gets complicated very quickly. 

Any idea?

**Comment by mcc05** [comment]
Please try the latest 2.1.3 version I've just uploaded, I'm going to run it for a few days to see if its fixed the timeout issue, as I only see it rarely

**Comment by boutch** [comment]
Thank you, just tried.
The first device on the list connects OK, the other ones below are returning timeout errors.

**Comment by mcc05** [comment]
Are the other devices working in HA, and displaying, and only the timeout errors on updates?

**Comment by boutch** [comment]
No, only one entity climate.lr_extension_uf is displayed in HA.

**Comment by mcc05** [comment]
Hi its hard to test for me as I only have one physical thermostat, I've edited the code again today and tried with multiple copies of the same physical  thermostat defined in HA and will run my code tonight and if all good will publish tomorrow for you to try

**Comment by willyk0** [comment]
I updated a moment ago to the new version and I have the timeout error (and entity unavaliable). I only have one thermostat, but there is another broadlink device in the network (one R3 mini for infrared devices). I don't know if this can help.

2020-06-23 23:25:55 ERROR (MainThread) [custom_components.hysen.climate] Failed to connect to Broadlink Hysen Climate device MAC:34:EA:34:_xx:xx:xx_, IP:_x.x.x.x_, Error:timed out

**Comment by mcc05** [comment]
Please try the latest version 2.1.4 just uploaded, I have ran this overnight with 10 thermostats in HA, again only one physical and let me know if it works

**Comment by willyk0** [comment]
No luck...

2020-06-24 17:43:32 ERROR (MainThread) [custom_components.hysen.climate] Failed to Authenticate with Broadlink Hysen Climate device:climate.termostato_salon , ('broadlink_response_error: ', 'The device is offline') 

2020-06-24 17:43:32 ERROR (MainThread) [custom_components.hysen.climate] Failed to add Broadlink Hysen Climate device:termostato_salon @192.168.x.x, 34:EA:34:x:x:x , to HA

EDIT: It's not offline, I can access it with using mobile app

**Comment by mcc05** [comment]
sorry please grab latest code I messed up discover add, are you specifying IP and MAC in your HA config or just MAC?

**Comment by mcc05** [comment]
What type of thermostat is it?

**Comment by mcc05** [comment]
All can you run the HA service climate.hysen_config_wifi
with the following 

ssid: yoursid
password: yourpassword
sectype: 4 
timeout: 5

and see what output you get in the log file

**Comment by willyk0** [comment]
- Updated last code, got this:


2020-06-24 18:14:28 ERROR (MainThread) [custom_components.hysen.climate] Failed to Authenticate with Broadlink Hysen Climate device:climate.termostato_salon , ('broadlink_response_error: ', 'The device is offline') 

2020-06-24 18:14:28 ERROR (MainThread) [custom_components.hysen.climate] Failed to add Broadlink Hysen Climate device:termostato_salon @192.x.x.x, 34:EA:34:xx:xx:xx , to HA

- my configuration:

climate:
  - platform: hysen
    devices:
      termostato_salon:
        name: Termostato Salon
        host: 192.168.x.x
        mac: "34:EA:34:xx:xx:xx"

- It worked until yesterday, when I updated it.

- It's a Floureon thermostat (same that Beok, the black one with white numbers)

- I ran that service with those parameters and got nothing in the log file, sorry. I did it twice but no luck...

**Comment by mcc05** [comment]
@willyk0 does the https://github.com/algirdasc/hass-components/tree/master/floureon  component work on yours as it using the latest broadlink code?

**Comment by willyk0** [comment]
Fixed for me! I can't understand why, but I realized that my thermostat stopped answering to my server's IP but worked from other devices, weird network behaviour. I rebooted the thermostat and started working as desired. Perhaps it got "stressed" with the acitivity since yesterday.

Thanks for your support!

**Comment by mcc05** [comment]
Great to hear, please test it let me know any issues you find, @boutch let me know how you get on!

**Comment by boutch** [comment]
Great work and great progress  Thank you so much. I can see 5 thermostats out of 7 in total in HA as climate entities. 

Both return the following error
2020-06-24 22:13:10 ERROR (MainThread) [custom_components.hysen.climate] Failed to Authenticate with Broadlink Hysen Climate device:climate.living_room_uf , ('broadlink_response_error: ', 'The device is offline')
2020-06-24 22:13:16 ERROR (MainThread) [custom_components.hysen.climate] Failed to Authenticate with Broadlink Hysen Climate device:climate.bathroom_uf , ('broadlink_response_error: ', 'The device is offline') 

Previously I was seeing the following error message x 45 times  (during 30min) but it is not appearing since I restarted HA.
2020-06-24 21:30:08 WARNING (SyncWorker_19) [custom_components.hysen.climate] Failed to Re-Authenticate with Broadlink Hysen Climate device:climate.living_room_uf , ('broadlink_response_error:', 'Control key is expired')

**Comment by willyk0** [comment]
@boutch the same happened with me with the same error, ping them from the server to check if they are answering. Mine worked with the official mobile app but didn’t answer to my server. A power cycle of the thermostat fixed that.

**Comment by boutch** [comment]
@mcc05 unfortunately the problem starts again.
Home assistant 0.117.5 - latest version of hysen

Logger: custom_components.hysen.climate
Source: custom_components/hysen/climate.py:948
Integration: hysen
First occurred: November 14, 2020, 10:18:18 PM (368 occurrences)
Last logged: 4:08:29 PM

Failed to get Data from Broadlink Hysen Climate device more than 3 times :climate.salome_uf,:('broadlink_response_error: ', 'The device is offline')
Failed to get Data from Broadlink Hysen Climate device more than 3 times :climate.lr_extension_uf,:('broadlink_response_error: ', 'The device is offline')
Failed to get Data from Broadlink Hysen Climate device more than 3 times :climate.bathroom_uf,:('broadlink_response_error: ', 'The device is offline')
Failed to get Data from Broadlink Hysen Climate device more than 3 times :climate.parents_uf,:('broadlink_response_error: ', 'The device is offline')
Failed to get Data from Broadlink Hysen Climate device more than 3 times :climate.living_room_uf,:('broadlink_response_error: ', 'The device is offline')

**Comment by mcc05** [comment]
@boutch sorry for the late reply, have you tried a power cycle or all your thermostats? I'm not having and issue :(

**Comment by gelmeone** [comment]
Hello,

I have just installed the latest version from the master branch and I can't connect to my thermostat Beok.
What am I doing wrong?

Log:
> 
> 
> Logger: custom_components.floureon
> Source: custom_components/floureon/__init__.py:63
> Integration: floureon (documentation, issues)
> First occurred: 05:40:52 (1 occurrences)
> Last logged: 05:40:52
> Thermostat 192.168.28.103 read_status error: [Errno -4000] Network timeout 
> 
> 
> 
> Logger: homeassistant.components.template.template_entity
> Source: components/template/template_entity.py:71
> Integration: template (documentation, issues)
> First occurred: 05:38:45 (4 occurrences)
> Last logged: 05:38:45
> 
>     TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template(""{{states.climate.house_thermostat.attributes.current_temperature}}"")' for attribute '_state' in entity 'sensor.house_thermostat_main_house_temp'
>     TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template(""{% if states.climate.house_thermostat.attributes.heating_active == 1 %}On{% else %}Off{% endif %}"")' for attribute '_state' in entity 'sensor.house_thermostat_heating_state'
>     TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{% if states.climate.house_thermostat.attributes.auto_override == 1 %}On{% else %}Off{% endif %}")' for attribute '_state' in entity 'sensor.house_thermostat_auto_override'
>     TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{states.climate.house_thermostat.attributes.external_temp}}")' for attribute '_state' in entity 'sensor.house_thermostat_externalsensortemp'
> 
> 
> 
> Logger: homeassistant.helpers.event
> Source: helpers/template.py:423
> First occurred: 05:38:45 (4 occurrences)
> Last logged: 05:38:45
> 
>     Error while processing template: Template(""{{states.climate.house_thermostat.attributes.current_temperature}}"")
>     Error while processing template: Template(""{% if states.climate.house_thermostat.attributes.heating_active == 1 %}On{% else %}Off{% endif %}"")
>     Error while processing template: Template("{% if states.climate.house_thermostat.attributes.auto_override == 1 %}On{% else %}Off{% endif %}")
>     Error while processing template: Template("{{states.climate.house_thermostat.attributes.external_temp}}")
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 421, in async_render
>     render_result = compiled.render(kwargs)
>   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
>     self.environment.handle_exception()
>   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
>     reraise(*rewrite_traceback_stack(source=source))
>   File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
>     raise value.with_traceback(tb)
>   File "<template>", line 1, in top-level template code
>   File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 407, in getattr
>     value = getattr(obj, attribute)
> jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 518, in async_render_to_info
>     render_info._result = self.async_render(variables, **kwargs)
>   File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
>     raise TemplateError(err) from err
> homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
> 
> 
> 
> Logger: custom_components.floureon.climate
> Source: custom_components/floureon/climate.py:76
> Integration: floureon (documentation, issues)
> First occurred: 05:38:42 (1 occurrences)
> Last logged: 05:38:42
> mac option is deprecated. It will be removed in future releases. Please modify your config accordingly. 
> 
> 
> 
> Logger: homeassistant.setup
> Source: setup.py:138
> First occurred: 05:38:42 (1 occurrences)
> Last logged: 05:38:42
> Setup failed for hysen: No setup function defined. 
> 
> 
> Logger: homeassistant.loader
> Source: loader.py:463
> First occurred: 05:38:42 (1 occurrences)
> Last logged: 05:38:42
> You are using a custom integration for floureon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

P.S. The https://github.com/algirdasc/hass-components/tree/master/floureon component work

**Comment by gelmeone** [comment]
I'm sorry. I installed it more carefully - everything worked. Great work! Thanks

**Comment by boutch** [comment]
I managed to get most of the thermostat back. They intermittently don't work on the Beok App so I suspect there is nothing from with the Hysen integration, it is probably network related. I'll close the issue. Thanks for your support.
