### ISSUE TITLE
device_state_attributes deprecated

### ISSUE THREAD

**Issue by camochu** [mairas/hysen#47]
After updating to Home Assistant 2021.12 this warning appears in logs:

> Logger: homeassistant.helpers.entity
> Source:` helpers/entity.py:549
> First` occurred: 20:25:57 (1 occurrences)
> Last logged: 20:25:57
> 
> Entity climate.termostato (<class 'custom_components.hysen.climate.HASS_Hysen_Climate_Device'>) implements device_state_attributes. Please report it to the custom component author.

As I read, it's necessary  to change 'device_state_attributes' with '**extra**_state_attributes'

**Comment by mcc05** [comment]
Hopefully fixed

**Comment by camochu** [comment]
I can confirm it's solved
Thanks for your great job!
