### ISSUE TITLE
ClimateEntityFeature error

### ISSUE THREAD

**Issue by boutch** [mairas/hysen#52]
Hello,

I am getting the below error
Platform error climate.hysen - cannot import name 'ClimateEntityFeature' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)".

Any idea please? Thank you

--

Versions
- Home Assistant 2022.4.7
- Hysen addon latest version

Configuration

climate:
  - platform: hysen
    devices:
      lr_extension_uf:
        name: LR Extension UF
        host: 192.168.XX.XXX
        mac: "34:EA:34:XX:XX:XX"
      living_room_uf:
        name: Living Room UF
        host: 192.168.XX.XX
        mac: "34:EA:34:XX:XX:XX"

**Comment by mcc05** [comment]
so you need to update HA to over 2022.5 or grab and older version of code for this component
