### ISSUE TITLE
Failed to Authenticate with Broadlink Hysen Climate

### ISSUE THREAD

**Issue by jaimecallejon** [mairas/hysen#55]
Logger: custom_components.hysen.climate
Source: custom_components/hysen/climate.py:547
Integration: hysen ([documentation](https://github.com/mairas/hysen), [issues](https://github.com/mairas/hysen/issues))
First occurred: 11:16:37 PM (2 occurrences)
Last logged: 11:16:37 PM

Failed to Authenticate with Broadlink Hysen Climate device:climate.beok_salon , ('broadlink_response_error: ', 'The device is offline')
Failed to add Broadlink Hysen Climate device:beok_salon @192.168.1.130, C8:F7:42:FA:**:** , to HA

Version: 028ad34
Configuration YAML
climate:
  - platform: hysen
    devices:
     beok_salon:
        name: beok_salon
        host: 192.168.1.130
        mac: "C8:F7:42:FA:**:**"

**Comment by jaimecallejon** [comment]
MODEL: BEOK TGR87

**Comment by tsaouste** [comment]
Hi,

I also have the same error for Hysen HY08-1

**Comment by mcc05** [comment]
Think both of these are not broadlink based so will not work with this integration

**Comment by tsaouste** [comment]
Is there any way to verify that? I integrated with Tuya but it only has on/off and temperature setting

**Comment by mcc05** [comment]
Tbh the fact it uses tuya means it's not based on the broadlink local api which this integration works with

**Comment by tsaouste** [comment]
Thank you for your fast responses. I am new to that hobby and learning. I suppose  I will rely on Tuya for now.

Br

**Comment by mcc05** [comment]
closed
