### ISSUE TITLE
Starting HA error

### ISSUE THREAD

**Issue by ghost** [mairas/hysen#9]
Dear, each time I restart home assistant I obtain some errors, but after that all works.
Can you fix it?
Thanks

home-assistant   | EXCEPTION(calculate): list index out of range
home-assistant   | EXCEPTION(calculate): list index out of rangeEXCEPTION(calculate): list index out of range
home-assistant   | 
home-assistant   | 2019-02-20 10:06:20 WARNING (SyncWorker_3) [custom_components.climate.hysen] Broadlink Hysen Device Clock Sync Success....
home-assistant   | 2019-02-20 10:06:20 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.cameretta fails
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
home-assistant   |     await self.async_device_update()
home-assistant   |   File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
home-assistant   |     await self.hass.async_add_executor_job(self.update)
home-assistant   |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
home-assistant   |     result = self.fn(*self.args, **self.kwargs)
home-assistant   |   File "/config/custom_components/climate/hysen.py", line 452, in update
home-assistant   |     self._HysenData = self._broadlink_device.get_full_status()
home-assistant   |   File "/usr/local/lib/python3.6/site-packages/broadlink/__init__.py", line 648, in get_full_status
home-assistant   |     payload = self.send_request(bytearray([0x01,0x03,0x00,0x00,0x00,0x16]))
home-assistant   |   File "/usr/local/lib/python3.6/site-packages/broadlink/__init__.py", line 612, in send_request
home-assistant   |     request_payload.append(crc & 0xFF)
home-assistant   | TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
home-assistant   | 2019-02-20 10:06:21 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.bagno fails

**Comment by mcc05** [comment]
Please try the latest version, I have improved the error handling, however this may be related to the potential issue @mairas has found in the broadlink.py dependency. Please let us know how the new version performs and re-open this if required.
